vich_uploader:
    db_driver: orm

    mappings:
        user_image:
            uri_prefix: '%app.path.user_image%'
            upload_destination: '%kernel.project_dir%/public%app.path.user_image%'

        article_image:
            uri_prefix: '%app.path.article_image%'
            upload_destination: '%kernel.project_dir%/public%app.path.article_image%'




